
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuizApp
{

using System;
    using System.Collections.Generic;
    
public partial class Attempt
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Attempt()
    {

        this.AttemptResponses = new HashSet<AttemptRespons>();

    }


    public int Id { get; set; }

    public int PlayerId { get; set; }

    public int TestId { get; set; }

    public Nullable<int> Result { get; set; }

    public short Archived { get; set; }

    public System.DateTime DateTaken { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AttemptRespons> AttemptResponses { get; set; }

    public virtual User User { get; set; }

    public virtual Test Test { get; set; }

}

}
