//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuizAppProjectEntities : DbContext
    {
        public QuizAppProjectEntities()
            : base("name=QuizAppProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< Updated upstream:QuizApp/QuizApp_dbContext.Context.cs
=======
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
>>>>>>> Stashed changes:QuizApp/QuizApp_DbContext.Context.cs
        public virtual DbSet<AttemptRespons> AttemptResponses { get; set; }
        public virtual DbSet<Attempt> Attempts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<TestQuestion> TestQuestions { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
