//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class attempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public attempt()
        {
            this.attempt_responses = new HashSet<attempt_responses>();
        }
    
        public int id { get; set; }
        public int player_id { get; set; }
        public int test_id { get; set; }
        public Nullable<int> result { get; set; }
        public short archived { get; set; }
        public System.DateTime date_taken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attempt_responses> attempt_responses { get; set; }
        public virtual user user { get; set; }
        public virtual test test { get; set; }
    }
}
